### PR TITLE
feat(swagger): Add go-swagger for validating Swagger spec

### PR DESCRIPTION
**Pull request by aalises**
Added [go-swagger](https://github.com/go-swagger/go-swagger) for validating `swagger.yml` with `make swagger-validate`, and also serving the API documentation website when running `make swagger-serve` which opens the docs on `http://localhost:51453/docs`.

Also, moved `swagger.yml` under `/api` to comply with the Golang Standard Layouts ™️ 😆 

Screenshot 2019-08-02 at 14 00 41

Swagger in Golang [still does not support OpenAPI 3.0](https://github.com/go-swagger/go-swagger/issues/1122) (😞 ) so the specifications have been adapted to the `2.0` standard, which serves for our purposes, and also made some changes to make the linting/validation pass (😄 ).

### CODE REVIEW

**Comment by fallion** [comment]
This requires downloading `swagger` manually right?

**Comment by aalises** [comment]
@fallion yes!! the same as with `prototool`. I tried also putting it in `mod` as a dependency but could not find the CLI and add

**Comment by fallion** [comment]
Have a look at https://github.com/kiwicom/iam/blob/194a6526287d5947106e3260777486a176e8e632/Makefile#L5 

You could add a makefile command that will download this.

**Comment by aalises** [comment]
@fallion Awesome! 🚀

**Pull request merged**
